<?php

define("STATUS_PRESUPUESTO_ANULADO", 3);
define("STATUS_INCIDENTE_ABIERTO", 1);
define("STATUS_INCIDENTE_APROBADO", 2);
define("INCIDENT_STATUS_RECHAZADO", 3);
define("STATUS_INCIDENT_RECHAZADO", 3);

define("STAGE_RUBRO_ASIGNADO", 1);
define("STAGE_PRESUPUESTO_CREADO", 3);
define("STAGE_PRESUPUESTO_ENVIADO", 4);
define("STAGE_PRESUPUESTO_APROBADO", 5);

define("RUBRO_A_ULTIMA_ETAPA", 5);
define("RUBRO_B_ULTIMA_ETAPA", 7);


define("RUBRO_A_RUBRO_ASIGNADO", 1);
define("RUBRO_A_MENSAJE_ENVIADO", 2);
define("RUBRO_A_TRABAJO_REALIZADO", 3);
define("RUBRO_A_CLIENTE_INFORMADO", 4);
define("RUBRO_A_PRESUPUESTO_CREADO", 5);

define("RUBRO_B_RUBRO_ASIGNADO", 1);
define("RUBRO_B_COMUNA_INFORMADA", 2);
define("RUBRO_B_PRESUPUESTO_CREADO", 3);
define("RUBRO_B_PRESUPUESTO_ENVIADO", 4);
define("RUBRO_B_PRESUPUESTO_APROBADO", 5);
define("RUBRO_B_TRABAJO_REALIZADO", 6);
define("RUBRO_B_TRABAJO_CERTIFICACION", 7);

define("PRESUPUESTO_STATUS_EN_CREACION", 1);
define("PRESUPUESTO_STATUS_APROBADO", 3);
define("PRESUPUESTO_STATUS_RECHAZADO", 5);

define("CLASIFICACION_RUBRO_A", 1);
define("CLASIFICACION_RUBRO_B", 2);

define("RUBRO_UNASSIGNED", 0);
define("RUBRO_A", 1);
define("RUBRO_B", 2);

define("ETAPA1_TEXTO", "Asignación de rubro");

define("PROGRESS_MAX_UPLOADS", 4);
