index:
    path: /
#    controller: Symfony\Bundle\FrameworkBundle\Controller\RedirectController::urlRedirectAction
    controller: App\Controller\DefaultController::index
    schemes: [https]
#    defaults:
#        path: /dishes
#        permanent: true

admin:
    path: /admin
    controller: Symfony\Bundle\FrameworkBundle\Controller\RedirectController::urlRedirectAction
    schemes: [https]
    defaults:
        path: /admin/dishes
        permanent: true

dashboard:
    path: /admin/dashboard
    controller: App\Controller\DashboardController::index
    schemes: [https]

#Public
show_menu:
    path:       /restaurant/{restaurantSlug}
    controller: App\Controller\ViewMenuController::showMenu
    defaults:
        restaurantSlug: 0
app_login:
    path: /login
    controller: App\Controller\SecurityController::login
    schemes: [https]

#Logged in
app_logout:
    path: /logout
    methods: GET

profile:
    path: /admin/user/profile
    controller: App\Controller\UserController::profileAction
view_menu_mobile:
    path:       /admin/show-preview-mobile
    controller: App\Controller\ViewMenuController::showPreview
    defaults:
        mobile:        true
view_menu_desktop:
    path:       /admin/show-preview-desktop
    controller: App\Controller\ViewMenuController::showPreview
    defaults:
        mobile:        false
show_restaurant:
    path:       /admin/restaurants
    controller: App\Controller\PageController::showRestaurants
show_page_settings:
    path:       /admin/page-settings
    controller: App\Controller\PageController::showPageSettings
show_page_order:
    path:       /admin/page-order
    controller: App\Controller\PageController::showPageOrder
show_categories:
    path:       /admin/categorias
    controller: App\Controller\PageController::showCategories
show_dishes:
    path:       /admin/dishes
    controller: App\Controller\PageController::showDishes

show_combos:
    path:       /admin/combos
    controller: App\Controller\PageController::showCombos
show_dishes_combos:
    path:       /admin/dishes-combos
    controller: App\Controller\PageController::showDishesCombos

page_update:
    path:       /admin/page/update/
    controller: App\Controller\PageController::updatePage
list_in_page_update:
    path:       /admin/page/update-list/
    controller: App\Controller\PageController::updateListInPage
user_list:
    path:       /admin/manage/users/
    controller: App\Controller\UserController::show
restaurant_list:
    path:       /admin/manage/restaurants/
    controller: App\Controller\RestaurantController::showRestaurantList
charts_linetot:
    path:       /admin/chartdata/linetotchart
    controller: App\Controller\ChartDataController::getLineTotalData
charts_linetot_by_day:
    path:       /admin/chartdata/linetotchartbyday
    controller: App\Controller\ChartDataController::getLineTotalDataByDay
charts_line:
    path:       /admin/chartdata/linechartperrestaurant
    controller: App\Controller\ChartDataController::getLineDataPerRestaurant
charts_line_by_day:
    path:       /admin/chartdata/linechartperrestaurantbyday
    controller: App\Controller\ChartDataController::getLineDataPerRestaurantByDay
charts_line_for_restaurant:
    path:       /admin/chartdata/linechartforrestaurant
    controller: App\Controller\ChartDataController::getLineTotalDataForRestaurant
charts_line_for_restaurant_by_day:
    path:       /admin/chartdata/linechartforrestaurantbyday
    controller: App\Controller\ChartDataController::getLineTotalDataForRestaurantByDay
table_users:
    path:       /admin/manage/tabledata-users/
    defaults:   { _controller: App\Controller\UserController::getTableData, dbuser: '%dbuser%', dbpw: '%dbpw%', dbhost: '%dbhost%', dbname: '%dbname%' }
    methods:    GET
table_restaurants:
    path:       /admin/manage/tabledata-restaurants/
    defaults:   { _controller: App\Controller\RestaurantController::getTableData, dbuser: '%dbuser%', dbpw: '%dbpw%', dbhost: '%dbhost%', dbname: '%dbname%' }
    methods:    GET
modal_data_edit_restaurant:
    path:       /admin/manage/modal/restaurant/edit/{id}
    controller: App\Controller\RestaurantController::modalShowEditRestaurant
modal_data_add_restaurant:
    path:       /admin/manage/modal/restaurant/add/
    controller: App\Controller\RestaurantController::modalShowAddRestaurant

user_update_user:
    path:       /admin/manage/user/update-user/
    controller: App\Controller\UserController::updateUser
user_delete_user:
    path:       /admin/manage/user/delete-user/
    controller: App\Controller\UserController::deleteUser
modal_data_edit_user:
    path:       /admin/manage/modal/user/edit/{id}
    controller: App\Controller\UserController::modalShowEditUser
modal_data_add_user:
    path:       /admin/manage/modal/user/add/
    controller: App\Controller\UserController::modalShowAddUser
user_add_user:
    path:       /admin/manage/user/add-user/
    controller: App\Controller\UserController::addUser
show_modal_select_font:
    path:       /admin/page/element/select-font/{key}
    controller: App\Controller\PageController::showSelectFont
show_modal_edit_image:
    path:       /admin/page/element/editImage/{imageId}
    controller: App\Controller\ImageController::editImage
show_modal_edit_category:
    path:       /admin/page/element/editCategory/{categoryId}
    controller: App\Controller\CategoryController::editCategory
show_modal_edit_combo:
    path:       /admin/page/element/editCombo/{comboId}
    controller: App\Controller\CategoryController::editCombo
show_modal_edit_restaurant:
    path:       /admin/page/element/editRestaurant/{restaurantId}
    controller: App\Controller\RestaurantController::edit
show_modal_edit_dish:
    path:       /admin/page/element/editDish/{dishId}
    controller: App\Controller\DishController::editDish
show_modal_add_image:
    path:       /admin/page/element/addImage/{sectionId}
    controller: App\Controller\ImageController::modalShowAddImage
show_modal_add_restaurant:
    path:       /admin/page/element/addRestaurant/
    controller: App\Controller\RestaurantController::modalShowAdd
show_modal_add_category:
    path:       /admin/page/element/addCategory/
    controller: App\Controller\CategoryController::modalShowAddCategory
show_modal_add_combo:
    path:       /admin/page/element/addCombo/
    controller: App\Controller\CategoryController::modalShowAddCombo
show_modal_add_dish:
    path:       /admin/page/element/addDish/
    controller: App\Controller\DishController::modalShowAddDish
show_modal_add_dish_to_combo:
    path:       /admin/page/element/addDishToCombo/{comboId}
    controller: App\Controller\ComboDishController::modalShowAddDishToCombo
show_modal_add_selected_dish_to_combo:
    path:       /admin/page/element/addSelectedDishToCombo/{dishId}
    controller: App\Controller\ComboDishController::modalShowAddSelectedDishToCombo
submit_add_image:
    path:       /admin/page/element/submitImage/{sectionId}
    controller: App\Controller\ImageController::submitForm
show_modal_add_equipamiento:
    path:       /admin/page/element/addEquipment/{pageId}
    controller: App\Controller\LaboratorioController::modalShowAddElement
submit_add_equipamiento:
    path:       /admin/page/element/submitEquipment/{pageId}
    controller: App\Controller\LaboratorioController::submitForm
submit_add_restaurant:
    path:       /admin/page/element/submitRestaurant/
    controller: App\Controller\RestaurantController::submitForm
submit_add_category:
    path:       /admin/page/element/submitCategory/
    controller: App\Controller\CategoryController::submitForm
submit_add_combo:
    path:       /admin/page/element/submitCombo/
    controller: App\Controller\CategoryController::submitFormAddCombo
submit_add_dish:
    path:       /admin/page/element/submitDish/
    controller: App\Controller\DishController::submitFormAddDish
submit_add_dish_to_combo:
    path:       /admin/page/element/submitDishToCombo/
    controller: App\Controller\ComboDishController::submitFormDishToCombo
submit_add_selected_dish_to_combo:
    path:       /admin/page/element/submitSelectedDishToCombo/
    controller: App\Controller\ComboDishController::submitFormSelectedDishToCombo
remove_restaurant:
    path:       /admin/page/element/removeRestaurant/{id}
    controller: App\Controller\RestaurantController::remove
remove_image_from_dish:
    path:       /admin/page/dish/removeImage/{dishId}
    controller: App\Controller\DishController::removeImageFromDish
remove_category:
    path:       /admin/page/element/removeCategory/{id}
    controller: App\Controller\CategoryController::remove
remove_combo:
    path:       /admin/page/element/removeCombo/{id}
    controller: App\Controller\CategoryController::remove
remove_dish:
    path:       /admin/page/element/removeDish/{id}
    controller: App\Controller\DishController::remove
remove_logo_from_restaurant:
    path:       /admin/page/restaurant/removeLogo/{restaurantId}
    controller: App\Controller\RestaurantController::removeLogo
remove_dish_from_combo:
    path:       /admin/page/element/removeDishFromCombo/{comboId}/{dishId}
    controller: App\Controller\ComboDishController::removeDishFromCombo
menu:
    path:       /admin/menu/
    controller: App\Controller\MenuController::index
api_get_config:
    path:       /api/config
    controller: App\Controller\Api\ConfigController::getConfig
api_login:
    path:       /api/login
    controller: App\Controller\Api\SecurityController::login
api_logout:
    path:       /api/logout
    controller: App\Controller\Api\SecurityController::logout
update_setting:
    path:       /admin/page/updateSetting/{key}/{property}/{value}
    controller: App\Controller\SettingsPagePreviewController::editSetting
update_image_setting:
    path:       /admin/page/updateImageSetting/{key}/{property}/{value}/{platform}
    controller: App\Controller\SettingsImageController::editSetting
clear_settings:
    path:       /admin/page/clearSettings
    controller: App\Controller\SettingsPagePreviewController::clearSettings
publish_settings:
    path:       /admin/page/publishSettings
    controller: App\Controller\SettingsPagePreviewController::publishSettings
category_update_order:
    path:       /admin/page/updateOrder/{id}/{newPosition}
    controller: App\Controller\SettingsPagePreviewController::updateCategoryOrder
category_toggle_visible:
    path:       /admin/category/toggleVisibility/{categoryId}
    controller: App\Controller\CategoryController::toggleVisibility
category_get_combo_count:
    path:       /admin/category/getComboCount/
    controller: App\Controller\CategoryController::getComboCount
dish_toggle_visible:
    path:       /admin/dish/toggleVisibility/{dishId}
    controller: App\Controller\DishController::toggleVisibility
dish_update_order_in_combo:
    path:       /admin/page/updateOrderInCombo/{dishId}/{categoryId}/{newPosition}
    controller: App\Controller\SettingsPagePreviewController::updateDishInComboOrder
dish_update_order_in_category:
    path:       /admin/page/updateOrderInCategory/{dishId}/{categoryId}/{newPosition}
    controller: App\Controller\SettingsPagePreviewController::updateDishInCategoryOrder
homepage:
    path:       /
    controller: App\Controller\DefaultController::index
