index:
    path: /
    controller: Symfony\Bundle\FrameworkBundle\Controller\RedirectController::urlRedirectAction
#    controller: App\Controller\DashboardController::index
    schemes: [https]
    defaults:
        path: /dishes
        permanent: true

homepage:
    path:       /dishes
    controller: App\Controller\PageController::showDishes

dashboard:
    path: /dashboard
    controller: App\Controller\DashboardController::index
    schemes: [https]

#Public
show_menu:
    path:       /restaurant/{restaurantSlug}
    controller: App\Controller\ViewMenuController::showMenu
    defaults:
        restaurantSlug: 0
app_login:
    path: /login
    controller: App\Controller\SecurityController::login
    schemes: [https]

#Logged in
app_logout:
    path: /logout
    methods: GET
profile:
    path: /user/profile
    controller: App\Controller\UserController::profileAction
view_menu_1:
    path:       /show-menu-preview-1
    controller: App\Controller\ViewMenuController::showPreview
    defaults:
        page:        1
view_menu_2:
    path:       /show-menu-preview-2
    controller: App\Controller\ViewMenuController::showPreview
    defaults:
        page:        2
show_restaurant:
    path:       /restaurants
    controller: App\Controller\PageController::showRestaurants
show_page_settings:
    path:       /page-settings
    controller: App\Controller\PageController::showPageSettings
show_page_order:
    path:       /page-order
    controller: App\Controller\PageController::showPageOrder
show_categories:
    path:       /categorias
    controller: App\Controller\PageController::showCategories
show_dishes:
    path:       /dishes
    controller: App\Controller\PageController::showDishes

show_combos:
    path:       /combos
    controller: App\Controller\PageController::showCombos
show_dishes_combos:
    path:       /dishes-combos
    controller: App\Controller\PageController::showDishesCombos

page_update:
    path:       /page/update/
    controller: App\Controller\PageController::updatePage
list_in_page_update:
    path:       /page/update-list/
    controller: App\Controller\PageController::updateListInPage
user_list:
    path:       /users/
    controller: App\Controller\UserController::show
charts_linetot:
    path:       /chartdata/linetotchart
    controller: App\Controller\ChartDataController::getLineTotalData
charts_line:
    path:       /chartdata/linechart
    controller: App\Controller\ChartDataController::getLineData
table_users:
    path:       /tabledata-users/
    defaults:   { _controller: App\Controller\UserController::getTableData, dbuser: '%dbuser%', dbpw: '%dbpw%', dbhost: '%dbhost%', dbname: '%dbname%' }
    methods:    GET
user_update_user:
    path:       /user/update-user/
    controller: App\Controller\UserController::updateUser
user_delete_user:
    path:       /user/delete-user/
    controller: App\Controller\UserController::deleteUser
modal_data_edit_user:
    path:       /modal/user/edit/{id}
    controller: App\Controller\UserController::modalShowEditUser
modal_data_add_user:
    path:       /modal/user/add/
    controller: App\Controller\UserController::modalShowAddUser
user_add_user:
    path:       /user/add-user/
    controller: App\Controller\UserController::addUser
show_modal_select_font:
    path:       /page/element/select-font/{key}
    controller: App\Controller\PageController::showSelectFont
show_modal_edit_image:
    path:       /page/element/editImage/{imageId}
    controller: App\Controller\ImageController::editImage
show_modal_edit_category:
    path:       /page/element/editCategory/{categoryId}
    controller: App\Controller\CategoryController::editCategory
show_modal_edit_combo:
    path:       /page/element/editCombo/{comboId}
    controller: App\Controller\ComboController::editCombo
show_modal_edit_restaurant:
    path:       /page/element/editRestaurant/{restaurantId}
    controller: App\Controller\RestaurantController::edit
show_modal_edit_dish:
    path:       /page/element/editDish/{dishId}
    controller: App\Controller\DishController::editDish
show_modal_add_image:
    path:       /page/element/addImage/{sectionId}
    controller: App\Controller\ImageController::modalShowAddImage
show_modal_add_restaurant:
    path:       /page/element/addRestaurant/
    controller: App\Controller\RestaurantController::modalShowAdd
show_modal_add_category:
    path:       /page/element/addCategory/
    controller: App\Controller\CategoryController::modalShowAddCategory
show_modal_add_combo:
    path:       /page/element/addCombo/
    controller: App\Controller\ComboController::modalShowAddCombo
show_modal_add_dish:
    path:       /page/element/addDish/
    controller: App\Controller\DishController::modalShowAddDish
show_modal_add_dish_to_combo:
    path:       /page/element/addDishToCombo/{comboId}
    controller: App\Controller\DishController::modalShowAddDishToCombo
show_modal_add_selected_dish_to_combo:
    path:       /page/element/addSelectedDishToCombo/{dishId}
    controller: App\Controller\DishController::modalShowAddSelectedDishToCombo
submit_add_image:
    path:       /page/element/submitImage/{sectionId}
    controller: App\Controller\ImageController::submitForm
show_modal_add_equipamiento:
    path:       /page/element/addEquipment/{pageId}
    controller: App\Controller\LaboratorioController::modalShowAddElement
submit_add_equipamiento:
    path:       /page/element/submitEquipment/{pageId}
    controller: App\Controller\LaboratorioController::submitForm
submit_add_restaurant:
    path:       /page/element/submitRestaurant/
    controller: App\Controller\RestaurantController::submitForm
submit_add_category:
    path:       /page/element/submitCategory/
    controller: App\Controller\CategoryController::submitForm
submit_add_combo:
    path:       /page/element/submitCombo/
    controller: App\Controller\ComboController::submitForm
submit_add_dish:
    path:       /page/element/submitDish/
    controller: App\Controller\DishController::submitForm
submit_add_dish_to_combo:
    path:       /page/element/submitDishToCombo/
    controller: App\Controller\DishController::submitFormDishToCombo
submit_add_selected_dish_to_combo:
    path:       /page/element/submitSelectedDishToCombo/
    controller: App\Controller\DishController::submitFormSelectedDishToCombo
remove_restaurant:
    path:       /page/element/removeRestaurant/{id}
    controller: App\Controller\RestaurantController::remove
remove_category:
    path:       /page/element/removeCategory/{id}
    controller: App\Controller\CategoryController::removeCategory
remove_combo:
    path:       /page/element/removeCombo/{id}
    controller: App\Controller\ComboController::removeCombo
remove_dish:
    path:       /page/element/removeDish/{id}
    controller: App\Controller\DishController::remove
remove_dish_from_combo:
    path:       /page/element/removeDishFromCombo/{comboId}/{dishId}
    controller: App\Controller\DishController::removeDishFromCombo
menu:
    path:       /menu/
    controller: App\Controller\MenuController::index
api_get_config:
    path:       /api/config
    controller: App\Controller\Api\ConfigController::getConfig
api_login:
    path:       /api/login
    controller: App\Controller\Api\SecurityController::login
api_logout:
    path:       /api/logout
    controller: App\Controller\Api\SecurityController::logout

update_setting:
    path:       /page/updateSetting/{id}/{property}/{value}
    controller: App\Controller\SettingsPageController::editSetting
